CREATE TABLE athlete (
  athlete_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  dob VARCHAR2(10) NOT NULL,
  gender VARCHAR2(10) NOT NULL CHECK (gender IN ('Male', 'Female', 'Other')),
  sport VARCHAR2(100) NOT NULL,
  enrollment_date VARCHAR2(10) NOT NULL
);
CREATE TABLE coach (
  coach_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  sport VARCHAR2(100) NOT NULL,
  phone VARCHAR2(20),
  email VARCHAR2(150) UNIQUE
);
CREATE TABLE training_session (
  session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_date VARCHAR2(10) NOT NULL,
  duration_minutes NUMBER NOT NULL CHECK (duration_minutes > 0),
  load_intensity NUMBER NOT NULL CHECK (
    load_intensity BETWEEN 1 AND 10
  ),
  athlete_id_fk NUMBER NOT NULL,
  coach_id_fk NUMBER NOT NULL,
  FOREIGN KEY (athlete_id_fk) REFERENCES athlete(athlete_id) ON DELETE CASCADE,
  FOREIGN KEY (coach_id_fk) REFERENCES coach(coach_id)
);
CREATE TABLE injury (
  injury_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  injury_type VARCHAR2(120) NOT NULL,
  severity VARCHAR2(20) NOT NULL CHECK (
    severity IN ('Low', 'Moderate', 'High', 'Critical')
  ),
  injury_date VARCHAR2(10) NOT NULL,
  description VARCHAR2(500),
  athlete_id_fk NUMBER NOT NULL,
  FOREIGN KEY (athlete_id_fk) REFERENCES athlete(athlete_id) ON DELETE CASCADE
);
CREATE TABLE recovery_metric (
  recovery_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_date VARCHAR2(10) NOT NULL,
  fatigue_level NUMBER NOT NULL CHECK (
    fatigue_level BETWEEN 1 AND 10
  ),
  muscle_soreness NUMBER NOT NULL CHECK (
    muscle_soreness BETWEEN 1 AND 10
  ),
  sleep_quality NUMBER NOT NULL CHECK (
    sleep_quality BETWEEN 1 AND 10
  ),
  athlete_id_fk NUMBER NOT NULL,
  FOREIGN KEY (athlete_id_fk) REFERENCES athlete(athlete_id) ON DELETE CASCADE,
  UNIQUE(metric_date, athlete_id_fk)
);
CREATE TABLE physiotherapist (
  physio_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  specialization VARCHAR2(120) NOT NULL,
  phone VARCHAR2(20),
  email VARCHAR2(150) UNIQUE
);
CREATE TABLE physiotherapy_session (
  physio_session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_date VARCHAR2(10) NOT NULL,
  treatment_type VARCHAR2(120) NOT NULL,
  duration NUMBER NOT NULL CHECK (duration > 0),
  injury_id_fk NUMBER NOT NULL,
  physio_id_fk NUMBER NOT NULL,
  FOREIGN KEY (injury_id_fk) REFERENCES injury(injury_id) ON DELETE CASCADE,
  FOREIGN KEY (physio_id_fk) REFERENCES physiotherapist(physio_id)
);
CREATE TABLE athlete_coach (
  athlete_id_fk NUMBER NOT NULL,
  coach_id_fk NUMBER NOT NULL,
  start_date VARCHAR2(10) NOT NULL,
  PRIMARY KEY (athlete_id_fk, coach_id_fk),
  FOREIGN KEY (athlete_id_fk) REFERENCES athlete(athlete_id) ON DELETE CASCADE,
  FOREIGN KEY (coach_id_fk) REFERENCES coach(coach_id) ON DELETE CASCADE
);